// src/constants/ageGroups.ts

export const AGE_GROUPS = {
  tiny: {
    id: 'tiny' as const,
    label: 'Tiny World',
    ageRange: '2-5',
    route: '/tiny',
    color: '#FF6B6B',
    bgColor: '#FFF8E7',
    lumoVariant: 'none' as const,
    maxSessionMinutes: 8,
    minTouchTarget: 80,
  },
  early: {
    id: 'early' as const,
    label: 'Adventure Academy',
    ageRange: '5-8',
    route: '/early',
    color: '#6C63FF',
    bgColor: '#F0F9FF',
    lumoVariant: 'pip' as const,
    maxSessionMinutes: 15,
    minTouchTarget: 60,
  },
  lab: {
    id: 'lab' as const,
    label: 'Lab Zero',
    ageRange: '8-10',
    route: '/lab',
    color: '#3B82F6',
    bgColor: '#F8FAFC',
    lumoVariant: 'peacock' as const,
    maxSessionMinutes: 20,
    minTouchTarget: 44,
  },
  discovery: {
    id: 'discovery' as const,
    label: 'Discovery Engine',
    ageRange: '10-13',
    route: '/discovery',
    color: '#6366F1',
    bgColor: '#0F172A',
    lumoVariant: 'sage' as const,
    maxSessionMinutes: 25,
    minTouchTarget: 44,
  },
  academy: {
    id: 'academy' as const,
    label: 'The Academy',
    ageRange: '13-15',
    route: '/academy',
    color: '#4F46E5',
    bgColor: '#0A0A0F',
    lumoVariant: 'ancient' as const,
    maxSessionMinutes: 999,
    minTouchTarget: 44,
  },
  explorer: {
    id: 'explorer' as const,
    label: 'Explorer',
    ageRange: '25+',
    route: '/explorer',
    color: '#8B5CF6',
    bgColor: '#1A1A2E',
    lumoVariant: 'peer' as const,
    maxSessionMinutes: 999,
    minTouchTarget: 44,
  },
  adult: {
    id: 'adult' as const,
    label: 'Lifelong Learners',
    ageRange: '18+',
    route: '/adult',
    color: '#334155',
    bgColor: '#F8FAFC',
    lumoVariant: 'none' as const,
    maxSessionMinutes: 999,
    minTouchTarget: 44,
  },
  crosscutting: {
    id: 'crosscutting' as const,
    label: 'Crosscutting',
    ageRange: 'All',
    route: '/crosscutting',
    color: '#10B981',
    bgColor: '#F0FDF4',
    lumoVariant: 'none' as const,
    maxSessionMinutes: 30,
    minTouchTarget: 44,
  },
  biology: {
    id: 'biology' as const,
    label: 'Bio Lab',
    ageRange: '10-18',
    route: '/biology',
    color: '#22C55E',
    bgColor: '#F0FDF4',
    lumoVariant: 'sage' as const,
    maxSessionMinutes: 30,
    minTouchTarget: 44,
  },
  math: {
    id: 'math' as const,
    label: 'Math Kingdom',
    ageRange: '5-18',
    route: '/math',
    color: '#A855F7',
    bgColor: '#FAF5FF',
    lumoVariant: 'none' as const,
    maxSessionMinutes: 30,
    minTouchTarget: 44,
  },
  physics: {
    id: 'physics' as const,
    label: 'PhysicsVerse',
    ageRange: '10-18',
    route: '/physics',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    lumoVariant: 'sage' as const,
    maxSessionMinutes: 30,
    minTouchTarget: 44,
  },
} as const;

export type AgeGroupId = keyof typeof AGE_GROUPS;
export type AgeGroup = AgeGroupId;
