// src/constants/languages.ts

export const LANGUAGES = {
  en: {
    code: 'en' as const,
    nativeName: 'English',
    fontFamily: '"Inter", "Nunito", sans-serif',
    googleFont: 'Inter:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Latin',
  },
  hi: {
    code: 'hi' as const,
    nativeName: 'हिंदी',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  ta: {
    code: 'ta' as const,
    nativeName: 'தமிழ்',
    fontFamily: '"Noto Sans Tamil", sans-serif',
    googleFont: 'Noto+Sans+Tamil:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Tamil',
  },
  te: {
    code: 'te' as const,
    nativeName: 'తెలుగు',
    fontFamily: '"Noto Sans Telugu", sans-serif',
    googleFont: 'Noto+Sans+Telugu:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Telugu',
  },
  kn: {
    code: 'kn' as const,
    nativeName: 'ಕನ್ನಡ',
    fontFamily: '"Noto Sans Kannada", sans-serif',
    googleFont: 'Noto+Sans+Kannada:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Kannada',
  },
  od: {
    code: 'od' as const,
    nativeName: 'ଓଡ଼ିଆ',
    fontFamily: '"Noto Sans Oriya", sans-serif',
    googleFont: 'Noto+Sans+Oriya:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Oriya',
  },
  mr: {
    code: 'mr' as const,
    nativeName: 'मराठी',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  bn: {
    code: 'bn' as const,
    nativeName: 'বাংলা',
    fontFamily: '"Noto Sans Bengali", sans-serif',
    googleFont: 'Noto+Sans+Bengali:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Bengali',
  },
  gu: {
    code: 'gu' as const,
    nativeName: 'ગુજરાતી',
    fontFamily: '"Noto Sans Gujarati", sans-serif',
    googleFont: 'Noto+Sans+Gujarati:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Gujarati',
  },
  ml: {
    code: 'ml' as const,
    nativeName: 'മലയാളം',
    fontFamily: '"Noto Sans Malayalam", sans-serif',
    googleFont: 'Noto+Sans+Malayalam:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Malayalam',
  },
  pa: {
    code: 'pa' as const,
    nativeName: 'ਪੰਜਾਬੀ',
    fontFamily: '"Noto Sans Gurmukhi", sans-serif',
    googleFont: 'Noto+Sans+Gurmukhi:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Gurmukhi',
  },
  as: {
    code: 'as' as const,
    nativeName: 'অসমীয়া',
    fontFamily: '"Noto Sans Bengali", sans-serif',
    googleFont: 'Noto+Sans+Bengali:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Bengali',
  },
  ur: {
    code: 'ur' as const,
    nativeName: 'اردو',
    fontFamily: '"Noto Nastaliq Urdu", serif',
    googleFont: 'Noto+Nastaliq+Urdu:wght@400;600;700',
    direction: 'rtl' as const,
    script: 'Arabic',
  },
  sa: {
    code: 'sa' as const,
    nativeName: 'संस्कृतम्',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  sat: {
    code: 'sat' as const,
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    fontFamily: '"Noto Sans Ol Chiki", sans-serif',
    googleFont: 'Noto+Sans+Ol+Chiki:wght@400;600;700',
    direction: 'ltr' as const,
    script: 'Ol Chiki',
  },
  ne: {
    code: 'ne' as const,
    nativeName: 'नेपाली',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  kok: {
    code: 'kok' as const,
    nativeName: 'कोंकणी',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  brx: {
    code: 'brx' as const,
    nativeName: 'बड़ो',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  doi: {
    code: 'doi' as const,
    nativeName: 'डोगरी',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  ks: {
    code: 'ks' as const,
    nativeName: 'کٲشُر',
    fontFamily: '"Noto Nastaliq Urdu", serif',
    googleFont: 'Noto+Nastaliq+Urdu:wght@400;600;700',
    direction: 'rtl' as const,
    script: 'Arabic',
  },
  mai: {
    code: 'mai' as const,
    nativeName: 'मैथिली',
    fontFamily: '"Noto Sans Devanagari", sans-serif',
    googleFont: 'Noto+Sans+Devanagari:wght@400;600;700;800',
    direction: 'ltr' as const,
    script: 'Devanagari',
  },
  sd: {
    code: 'sd' as const,
    nativeName: 'سنڌي',
    fontFamily: '"Noto Nastaliq Urdu", serif',
    googleFont: 'Noto+Nastaliq+Urdu:wght@400;600;700',
    direction: 'rtl' as const,
    script: 'Arabic',
  },
  mni: {
    code: 'mni' as const,
    nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ',
    fontFamily: '"Noto Sans Meetei Mayek", sans-serif',
    googleFont: 'Noto+Sans+Meetei+Mayek:wght@400;600;700',
    direction: 'ltr' as const,
    script: 'Meitei Mayek',
  },
} as const;

export type LanguageCode = keyof typeof LANGUAGES;
