import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { cn } from '../../../utils/cn';

interface LearnPhaseProps { onComplete: () => void; }

const scenarios = [
  { image: '📰', title: '"Breaking News: Dogs Can Now Fly!"', real: false, explanation: "This is AI-generated fake news! Dogs can't fly. Always check multiple trusted sources before believing surprising headlines." },
  { image: '📸', title: 'A photo of your friend at school', real: true, explanation: "This is likely real — it matches what you know. But deepfakes can fake photos too, so context matters!" },
  { image: '🎤', title: 'A voice message from a celebrity asking for money', real: false, explanation: "This is likely a deepfake voice clone! Celebrities don't call random people asking for money. Big red flag!" },
  { image: '📝', title: 'Your homework assignment from your teacher\'s website', real: true, explanation: "If it's from your school's official site, it's real. Always verify the source URL!" },
  { image: '🖼️', title: 'A perfect photo of a unicorn in a real city', real: false, explanation: "Unicorns aren't real! This was likely generated by an AI image tool. Beautiful, but fake!" },
];

export default function LearnPhase({ onComplete }: LearnPhaseProps) {
  const { t } = useTranslation();
  const [currentScenario, setCurrentScenario] = useState(0);
  const [answer, setAnswer] = useState<boolean | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [score, setScore] = useState(0);

  const scenario = scenarios[currentScenario];
  const handleAnswer = (isFake: boolean) => {
    if (showResult) return;
    const correct = (isFake && !scenario.real) || (!isFake && scenario.real);
    setAnswer(isFake);
    setShowResult(true);
    if (correct) setScore(s => s + 1);
  };

  const nextScenario = () => {
    if (currentScenario < scenarios.length - 1) {
      setCurrentScenario(s => s + 1);
      setAnswer(null);
      setShowResult(false);
    }
  };

  const allDone = currentScenario === scenarios.length - 1 && showResult;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-3xl shadow-xl overflow-hidden">
        <div className="bg-gradient-to-r from-sky-500 to-blue-600 p-4 sm:p-6 text-white">
          <div className="flex justify-between items-center">
            <div>
              <h2 className="text-xl sm:text-2xl font-bold">🔮 Spot the Fake!</h2>
              <p className="text-sky-100 mt-1 text-sm">Can you tell what's real and what's AI-generated?</p>
            </div>
            <div className="text-right">
              <div className="text-xl font-bold">{score}/{scenarios.length}</div>
              <div className="text-xs text-sky-200">{currentScenario + 1} of {scenarios.length}</div>
            </div>
          </div>
        </div>

        <div className="p-4 sm:p-6">
          {/* Scenario */}
          <div className="bg-gray-50 rounded-2xl p-6 mb-6 text-center">
            <span className="text-5xl block mb-4">{scenario.image}</span>
            <p className="text-lg font-medium text-gray-800">"{scenario.title}"</p>
          </div>

          {/* Buttons */}
          {!showResult && (
            <div className="grid grid-cols-2 gap-4 mb-6">
              <button onClick={() => handleAnswer(false)} className="p-4 bg-green-50 border-2 border-green-200 rounded-xl font-bold text-green-700 hover:bg-green-100 transition-all hover:scale-[1.02]">✅ Looks Real!</button>
              <button onClick={() => handleAnswer(true)} className="p-4 bg-red-50 border-2 border-red-200 rounded-xl font-bold text-red-700 hover:bg-red-100 transition-all hover:scale-[1.02]">{t('auto.worlds_ai_components_concepts_AISafety_LearnPhase.it_s_fake', "🚫 It's Fake!")}</button>
            </div>
          )}

          {/* Result */}
          {showResult && (
            <div className={cn("p-4 rounded-xl mb-6", (answer === !scenario.real) ? "bg-green-50 border-l-4 border-green-500" : "bg-orange-50 border-l-4 border-orange-500")}>
              <p className="font-bold mb-1">{(answer === !scenario.real) ? "🎉 Correct!" : "🤔 Not quite!"}</p>
              <p className="text-gray-700 text-sm">{scenario.explanation}</p>
            </div>
          )}

          {showResult && !allDone && (
            <button onClick={nextScenario} className="w-full py-3 bg-gradient-to-r from-sky-500 to-blue-600 text-white rounded-xl font-medium hover:shadow-lg">{t('auto.learning.s880_next_scenario', 'Next Scenario →')}</button>
          )}

          {allDone && (
            <div className="text-center">
              <p className="text-lg font-bold text-gray-800 mb-2">You spotted {score}/{scenarios.length} correctly!</p>
              <p className="text-gray-600 mb-4 text-sm">Great detective work! Always think critically about content you see online.</p>
              <button onClick={onComplete} className="px-6 py-3 bg-gradient-to-r from-sky-500 to-blue-600 text-white rounded-xl font-medium hover:shadow-lg transition-all hover:scale-105">
                Now let me try! 🧸
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
